# Generated by Django 5.2.6 on 2025-11-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_messagereply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagereply',
            options={'ordering': ['created_at']},
        ),
    ]
