# Generated by Django 5.2.6 on 2025-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='student_photos/'),
        ),
    ]
