# Generated by Django 5.2.6 on 2025-10-30 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('assigned_streams', models.ManyToManyField(blank=True, to='school.stream')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher_name', models.CharField(blank=True, help_text='Used for substitutes or external teachers without a system record.', max_length=120)),
                ('is_substitution', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('teacher_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='school_admin.teacherrecord')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('stream', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
