# Generated by Django 5.2.6 on 2025-11-05 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_academicyear_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladminprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schooladminprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='schooladminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schooladminprofile',
            name='phone',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schooladminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_admins/'),
        ),
        migrations.AlterField(
            model_name='schooladminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
