# Generated by Django 5.2.6 on 2025-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0004_remove_schooladminprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladminprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_duty', 'On Duty'), ('away', 'Away')], default='active', max_length=20),
        ),
    ]
