# Generated by Django 5.2.6 on 2025-11-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_school_admin',
            field=models.BooleanField(default=False),
        ),
    ]
