# Generated by Django 5.2.6 on 2025-11-05 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
