# Generated by Django 5.2.6 on 2025-11-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_duty', 'On Duty'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
