# Generated by Django 5.2.6 on 2025-11-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_photos/'),
        ),
    ]
