# Generated by Django 5.2.6 on 2025-11-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_parentprofile_address_parentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
    ]
